# Generated by Django 5.2.4 on 2026-04-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_currency_user_otp_created_at_user_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
